# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
	if is_ci
      create_keychain(
        name: ENV['MATCH_KEYCHAIN_NAME'],
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
    end

	increment_build_number(
		build_number: latest_testflight_build_number + 1
	)

	match(
      type: "appstore",
      readonly: is_ci,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"]
    )

	build_app(
      workspace: "Runner.xcworkspace",
      scheme: "MyApp",
      export_method: "app-store"
    )
	upload_to_testflight(
		skip_waiting_for_build_processing: true
	)
	slack(
		message: "Testflight 배포 성공!🚀",
		slack_url: "https://hooks.slack.com/services/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"
	)
  end

  platform :ios do

	error do |lane, exception, options|
		slack(
			message: "에러 발생 ${exception}",
			success: false,
			slack_url: "https://hooks.slack.com/services/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"
		)
	end
  end
end
