name: Demo App Release

on:
  push:
    branches: [ main ]

jobs:
  drive_android:
    runs-on: macos-latest
    #creates a build matrix for your jobs
    strategy:
      matrix:
        device:
          - "pixel"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.3'
      - run: flutter doctor -v
      - run: flutter clean
      - run: flutter pub get
      - name: create setenv.sh
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: ${{ matrix.device }}
          script: |
            flutter drive --target=test_driver/app.dart
